### ISSUE TITLE
Add a drop-down menu to the toolbar for quick access to output nodes.

### ISSUE THREAD

**Issue by zdirtywork** [SolarianZ/UnityPlayableGraphMonitorTool#12]
Useful when browsing a large PlayableGraph.

**Comment by SolarianZ** [comment]
Added in [v2.4.0](https://github.com/SolarianZ/UnityPlayableGraphMonitorTool/releases/tag/v2.4.0).

Known issue:
- The select node dropdown menus requires two clicks to display the latest content.
