### ISSUE TITLE
Dublicated graph item

### ISSUE THREAD

**Issue by zgamedog** [SolarianZ/UnityPlayableGraphMonitorTool#15]
![1111](https://github.com/SolarianZ/UnityPlayableGraphMonitorTool/assets/17020783/b70f2d37-d325-40be-9853-70592f8c1e10)

**Comment by zdirtywork** [comment]
Hi, can you submit a simple project that reproduces this problem?

**Comment by SolarianZ** [comment]
Close this issue because it cannot be reproduced and the requester has not responded for a long time.
