### ISSUE TITLE
Can you please add auto clean-up of the graph tool  on Editor going into PlayMode?

### ISSUE THREAD

**Issue by studentutu** [SolarianZ/UnityPlayableGraphMonitorTool#18]
Can you please add auto clean-up of the graph tool  on Editor going into PlayMode?
Currently, graph stays at is was after exiting play mode, which is very useful, but then we need to start again whole editor or recompile to clean-up before going into next playmode session.
It would be very nice to clean-up all graphs and all cache on editor going into playmode.

**Comment by zdirtywork** [comment]
> Currently, graph stays at is was after exiting play mode

The graph tool will only display active graphs. If the graph is still displayed after exiting play mode, it means that the graph has not been destroyed.

**Comment by zdirtywork** [comment]
See the last paragraph of this document: https://docs.unity3d.com/Manual/Playables-Graph.html

> Destroy a PlayableGraph manually with the `PlayableGraph.Destroy()` method. This method automatically destroys all playables and playable outputs that were created by the PlayableGraph. You **must manually call** this destroy method to destroy a PlayableGraph, otherwise Unity issues an error message.

**Comment by studentutu** [comment]
Already made change in our local repo in PlayableGraphMonitorWindow.cs, 
  ```
  public static void ClearGraphs()
    {
      _graphs.Clear();
      _graphs.Add(new PlayableGraph());

      var instance = _instance;
      if (instance?._graphPopupField != null)
        instance._graphPopupField.value = _graphs[0];

      instance?._graphPopupField?.MarkDirtyRepaint();
      instance?._toolbar?.MarkDirtyRepaint();

      instance?.UpdatePlayableGraphPopupField();
    }
```
and just add an editor script with a subscription to Editor.PlaymodeCHange

```
  public static class EditorPlaymodeChange
  {
    [InitializeOnEnterPlayMode]
    public static void ClearOnEnterPlayMode()
    {
      GraphTool.ClearGlobalCache();
      PlayableGraphMonitorWindow.ClearGraphs();
    }
  }
```
